# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/github-workflow.json
name: CD
run-name: Running continuous deployment on ${{ github.actor }}'s commits

permissions:
  contents: read

on:
  push:
    tags:
      - "*"

concurrency:
  group: cd
  cancel-in-progress: false

jobs:
  promoteImage:
    name: Promote image to ${{ github.ref_name }} (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-latest
          - arch: arm64
            runner: ubuntu-24.04-arm

    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 2

      - name: Setup Pipeline
        uses: tahminator/pipeline/actions/setup@8601c1c7d28289879772574a60fe817fb953eeee # 1.0.93
        with:
          SECRETS: ${{ toJSON(secrets) }}
          LINT_CI: true

      - name: Get parent SHA
        id: parent
        run: echo "sha=$(git rev-parse ${{ github.sha }}^1)" >> "$GITHUB_OUTPUT"

      - name: Promote image
        uses: ./.github/composite/promote-image
        with:
          RELEASE_TAG: ${{ github.ref_name }}
          SHA: ${{ steps.parent.outputs.sha }}
          ARCH: ${{ matrix.arch }}

  deployProduction:
    name: Deploy to production
    runs-on: ubuntu-latest
    needs: [promoteImage]

    concurrency:
      group: deploy-production
      cancel-in-progress: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Pipeline
        uses: tahminator/pipeline/actions/setup@8601c1c7d28289879772574a60fe817fb953eeee # 1.0.93
        with:
          SECRETS: ${{ toJSON(secrets) }}
          LINT_CI: true

      - name: Deploy client
        uses: ./.github/composite/deploy
        with:
          RELEASE_TAG: ${{ github.ref_name }}
